if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'tpope/vim-surround'
Plug 'tpope/vim-eunuch'
call plug#end()

colo dracula 

set termguicolors
syntax enable
set background=dark

set number
set laststatus=2

set clipboard=unnamedplus
set nocompatible

nnoremap d "_d
nnoremap D "_D
vnoremap d "_d
nnoremap <C-S> :update<cr>
inoremap <C-S> <C-O>:update<cr>
